### ISSUE TITLE
is anyone using this at scale? (we will probably have 10000 end clients with 5 socket.io nodes)

### ISSUE THREAD

**Issue by scalebig** [elegantmonkeys/socket.io-pubsub#14]
is anyone using this at scale? We will probably have 10000 end clients with 5 socket.io nodes - we are an education company and are projecting > 22k students total with a worst case of 10K online at the same time (but reality is ~5K).

We are tied into Google Cloud pretty tightly now. GKE, Google Storage, etc. So this would be great instead of adding another redis instance (for the redis-adapter) to maintain.

**Comment by idoshamun** [comment]
Not as far I know, I haven't use it at scale but it's worth testing.
This package relies on Google Pub/Sub and does nothing fancy so I can't see a fair reason it will cause issues.

**Comment by RyanCopley** [comment]
@scalebig -- Did you ever test this? I would love to hear what you learned.
