### ISSUE TITLE
Release new version with actual changes

### ISSUE THREAD

**Issue by MaxSchaefer** [elegantmonkeys/socket.io-pubsub#23]
The [commit ](https://github.com/elegantmonkeys/socket.io-pubsub/commit/ed46ae027e50268133f8b1544caba78dddbe3711)fixed following error:
`TypeError: this.topics[topic].publisher is not a function`.
This imporant commit **is not** in the actual Version.

Do you want to release these changes?
Otherwise the error continues to occur in the actual Version.

**Comment by idoshamun** [comment]
Released in 2.0.4, thanks for letting me know
