### ISSUE TITLE
Using socket.io-emitter?

### ISSUE THREAD

**Issue by gh2k** [elegantmonkeys/socket.io-pubsub#25]
The `README` suggests that we can use `socket.io-emitter` to emit events from other processes. However, this appears to be redis-specific.

Should this link be there? Is there a way to emit messages from a different process using this adapter?

**Comment by idoshamun** [comment]
Hi @gh2k,
I'm not highly familiar with `socket.io-emitter`, unfortunately.
Could you elaborate on your use case and maybe I can help out with a proper solution?

**Comment by gh2k** [comment]
Thanks - I was confused by the link to `socket.io-emitter` in the README. I'm wondering if we don't need `emitter` at all? (And this was copypasted from the original redis adapter)

For my use case, I would like a separate process (a cloud function) to send a message to connected users, that isn't running a socket.io instance with clients connected.

Might this be possible by simply creating an instance and emitting to a room? - For example, something like ~some code~ [edit], see reply
?

**Comment by gh2k** [comment]
Answering my own question, yes that seems to work.

More specifically, my code looks like this:
```JavaScript
const Io = require('socket.io')
const PubSub = require('@google-cloud/pubsub')
const Adapter = require('socket.io-pubsub')

const pubsubClient = new PubSub.PubSub()
const io = Io({ adapter: Adapter(pubsubClient, {}) })

module.exports = emitToRoom(room, message, payload) {
  io.to(room).emit(message, payload)
}
```

**Comment by idoshamun** [comment]
Yes, that's perfect!
The good thing about Google Pub/Sub is that it's a standalone infrastructure so it's agnostic to whether you run it in a different process or a different server. Unlike the basic `emitter` which is probably based on inter-process communication.
