### ISSUE TITLE
Any plans to refactor to work with updated google-cloud and socket.io-adapter?

### ISSUE THREAD

**Issue by k00k** [elegantmonkeys/socket.io-pubsub#6]
As Google no longer recommends using the meta-package of google-cloud anymore, I was just curious, do you have any plans to upgrade this module to use the individual [@google-cloud/pubsub](https://github.com/googlecloudplatform/google-cloud-node#cloud-pubsub-alpha) package? I tried just plugging it in, but I get an error of  `TypeError: this.adapter.addAll is not a function`. Which I believe is actually related to the "new" way that [socket.io-adapter](https://github.com/socketio/socket.io-adapter) is coded and expecting other adapters to have functions like `addAll` and  the `Room` constructor.

Sorry, I know this actually kinda 2 issues. I'd take a stab at a PR, but I'm just diving into this socket.io adapter world.

**Comment by k00k** [comment]
I should add, I was using the following versions:

`@google-cloud/pubsub: ^0.11.0`
`socket.io-adapter: ^1.1.0`

**Comment by idoshamun** [comment]
Actually I stopped using this package for a little while, but I'll try to resolve this issue.

**Comment by idoshamun** [comment]
Published in v1.1.0

**Comment by k00k** [comment]
Thanks for the quick work @idoshamun - That was a big help to me!

**Comment by idoshamun** [comment]
@k00k no problem! I would really appreciate feedback after you try the new version for a little while. what's missing? is everything works ok? etc. Enjoy coding :+1:

**Comment by k00k** [comment]
@idoshamun Just tried it out, and it worked great! Started right up with no problem. 

As I said, I'm new to socket.io adapters and google pub-sub. I have 2 Google compute engine instances behind a load balancer and each instance has a socket.io server running. Messaging over the sockets seems a little laggy when clients are connected to the different compute engine instances. I guess that's probably to be expected?

**Comment by idoshamun** [comment]
Yes it is expected compared to only one instance which serves everyone, there is the latency of publishing a message to google pubsub and receiving it by the other instance. It shouldn't be a high latency though, especially if you're compute instances are in the region and zone.

**Comment by k00k** [comment]
Yes, pretty much what I determined. It's not awful lag, but could be better. I'm making a multiplayer game server, so it's something I want to limit the lag on. One thought is that when a user joins a room, if he's not on the same server as that room's host, then the client app could automatically disconnect and rejoin directly to that same host instance without going through the load balancer.

**Comment by idoshamun** [comment]
It's a great idea I would go for it for minimizing latency, especially if you're building a real time multiplayer game.
